### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by HappyDay-design** [AntonioAlgaida/Reinforcement-Autonomous-Intersection-Management--RAIM#1]
Hello

I am very grateful to you for sharing your code
I have run your model on Ubuntu. I have to create the new `results` folder for tripinfo.xml
There are a lot of collision when training
And all traffic lights are green. It is the `FixedAlgorithm`. Could you show me how to change to DRL?
![image](https://user-images.githubusercontent.com/82990411/189527518-908f31a4-12e3-4a1b-ba7f-6c2bc2cee263.png)

**Comment by HappyDay-design** [comment]
I see that there are many algorithms in the `algorithms` folder?
How could I change algorithms in main_1_1_v2.py?
Thanks

**Comment by AntonioAlgaida** [comment]
Hi,

To change the algorithm you need to change lane 99 in `main_1_1_v2.py`

By default is used the fixed traffic light algorithm with a green time defined by: `greentime=(120-10)//2`

If you want to change by other traditional traffic lights algorithms, you need to instantiate in the previous lane.
Like: `algorithm = REDVDAlgorithm(...)`
Changing `Fixed` by `algorithm`

If you want to use the proposed algorithm, you need to instantiate the module located in `TD3PER`
`algorithm = TD3Agent.Agent(...)`

Best,
